<?php
/**
 * TL_ROOT/system/modules/i18nl10n/languages/de/default.php 
 * 
 * Contao extension: i18nl10n 0.2.0 stable 
 * German translation file 
 * 
 * Copyright : &copy; 2010, 2011 
 * License   : LGPLv3 
 * Author    : Krasimir Berov (kberov), http://bulgarian-creative-circle.org/ 
 * Translator: Luciano Sportelli (ciaobello), http://www.ciaobello.luciano.ch/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['i18nl10n_fields']['language']['label']['0'] = "Sprache";
$GLOBALS['TL_LANG']['MSC']['i18nl10n_fields']['language']['label']['1'] = "Bitte wählen Sie eine Sprache";
$GLOBALS['TL_LANG']['MSC']['editl10ns'] = "Sprache für Seite %s ändern";
$GLOBALS['TL_LANG']['MSC']['language'] = "Sprache";
$GLOBALS['TL_LANG']['LNG'][''] = "Alle";
 
?>
