<?php
/**
 * TL_ROOT/system/modules/i18nl10n/languages/de/modules.php 
 * 
 * Contao extension: i18nl10n 0.2.0 stable 
 * German translation file 
 * 
 * Copyright : &copy; 2010, 2011 
 * License   : LGPLv3 
 * Author    : Krasimir Berov (kberov), http://bulgarian-creative-circle.org/ 
 * Translator: Luciano Sportelli (ciaobello), http://www.ciaobello.luciano.ch/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['i18nl10n']['0'] = "Mehrsprachige Seiten";
$GLOBALS['TL_LANG']['MOD']['i18nl10n']['1'] = "Ermöglicht die Verwaltung mehrsprachiger Seiten in einem einzigen Seitenbaum. Bietet dazu auch sprach gebundene Inhaltselemente an.";
$GLOBALS['TL_LANG']['FMD']['i18nl10nnav']['0'] = "Sprachmenü";
$GLOBALS['TL_LANG']['FMD']['i18nl10nnav']['1'] = "Erstellt ein Menü um zwischen Seiten und Sprachen zu wechseln.";
 
?>
