<?php
/**
 * TL_ROOT/system/modules/i18nl10n/languages/de/tl_content.php 
 * 
 * Contao extension: i18nl10n 0.2.0 stable 
 * German translation file 
 * 
 * Copyright : &copy; 2010, 2011 
 * License   : LGPLv3 
 * Author    : Krasimir Berov (kberov), http://bulgarian-creative-circle.org/ 
 * Translator: Luciano Sportelli (ciaobello), http://www.ciaobello.luciano.ch/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['l10n_legend'] = "L10N Einstellungen";
 
?>
