<?php
/**
 * TL_ROOT/system/modules/i18nl10n/languages/de/tl_page_i18nl10n.php 
 * 
 * Contao extension: i18nl10n 0.2.0 stable 
 * German translation file 
 * 
 * Copyright : &copy; 2010, 2011 
 * License   : LGPLv3 
 * Author    : Krasimir Berov (kberov), http://bulgarian-creative-circle.org/ 
 * Translator: Luciano Sportelli (ciaobello), http://www.ciaobello.luciano.ch/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['menu_legend'] = "Lokalisierte Felder für Menü und URL";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['meta_legend'] = "Lokalisierte Meta-Felder für den <head></head> Bereich.";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['time_legend'] = "Lokalisierte Datum und Zeit Einstellungen";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['new']['0'] = "Neue L10N";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['new']['1'] = "Neue Lokalisierte Seite hinzufügen";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['edit']['0'] = "Bearbeiten";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['edit']['1'] = "Lokalisierte Seite %s bearbeiten";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['copy']['0'] = "Duplizieren";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['copy']['1'] = "Lokalisierte Seite %s duplizieren";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['delete']['0'] = "Löschen";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['delete']['1'] = "Lokalisierte Seite %s löschen";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['show']['0'] = "Anzeigen";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['show']['1'] = "Details der lokalisierten Seite %s anzeigen";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['localize_all']['0'] = "L10N für Alle";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['localize_all']['1'] = "Alle nicht lokalisierten Seiten mit vorhandenen Sprachen lokalisieren";
$GLOBALS['TL_LANG']['tl_page_i18nl10n']['localize_all_q'] = "Für alle nicht lokalisierten Seiten in <span style=\"white-space:nowrap\">[%s]</span> werden lokalisierte Seiten in den vorhandenen Sprachen erstellt.<br />Sind Sie sicher, dass Sie für alle nicht lokalisierten Seiten, Lokalisierungen erstellen wollen?";
 
?>
