<?php
/**
 * TL_ROOT/system/modules/i18nl10n/languages/de/tl_settings.php 
 * 
 * Contao extension: i18nl10n 0.2.0 stable 
 * German translation file 
 * 
 * Copyright : &copy; 2010, 2011 
 * License   : LGPLv3 
 * Author    : Krasimir Berov (kberov), http://bulgarian-creative-circle.org/ 
 * Translator: Luciano Sportelli (ciaobello), http://www.ciaobello.luciano.ch/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['page_i18nl10n'] = "Mehrsprachige Seiten";
$GLOBALS['TL_LANG']['tl_settings']['i18nl10n_languages']['0'] = "Sprachen";
$GLOBALS['TL_LANG']['tl_settings']['i18nl10n_languages']['1'] = "Bitte fügen Sie\n          <a target=\"_blank\" \n          href=\"http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes\"><em> ISO 639-1</em></a>\n          valide Sprach-Codes hinzu (z.B. <em>en</em> oder <em>de</em>). Fügen Sie nur Ihre gewünschten Sprachen hinzu.";
$GLOBALS['TL_LANG']['tl_settings']['i18nl10n_default_language']['0'] = "Standardsprache";
$GLOBALS['TL_LANG']['tl_settings']['i18nl10n_default_language']['1'] = "Geben Sie die Standardsprache Ihrer Seite an. Ein Inhalts-Element in dieser Sprache sollte als Fallback immer vorhanden sein";
$GLOBALS['TL_LANG']['tl_settings']['i18nl10n_alias_suffix']['0'] = "Sprachkürzel als Suffix";
$GLOBALS['TL_LANG']['tl_settings']['i18nl10n_alias_suffix']['1'] = "Die entsprechende Sprache wird in Echtzeit an den Alias angehängt. (z.B. index - > index.en, index.de usw.). Die Seitensprache wird dem Alias entsprechend erraten. Der eigentliche URL-Suffix wird zum Schluss angehängt (z.B. index.de.html). Beachten Sie! Dies ändert dynamisch erzeugte Links in Menüs, aber nicht Ihre Seitenaliase. Sie können es jederzeit wieder ausschalten.";
 
?>
